# Setup
title:               Melinda Shore
tagline:             'Miscellaneous things'
description:         
url:                 https://melindashore.github.io
baseurl:             
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Melinda Shore
  url:               
  email:             melinda.shore@nomountain.net

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             0.1.1
google_analytics_id: #UA-XXXX-Y
